name: CI

on:
  schedule:
    # Run every Sunday at 00:00 PM
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: "0 0 * * SUN"
  push:
    branches:
      - master
      - rec-*
      - dev-*
  pull_request:
    branches:
      - master
      - rec-*
      - dev-*
      - dependabot/*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, 3.10.0-beta.1 ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/release.txt
        pip install -e .
    - name: Configure and Run Application
      run: |
        weather --version
        weather config --token ${{ secrets.TOKEN }}
        weather config --unit-system si
        weather config --location madrid
        weather config --list
        weather --verbose report --location tokyo --save
        weather report --list
        weather log --list
